import type { RunSummary } from "../types.js";

// Markdown summary for PR comments (used by the GitHub Action).
export function reportMarkdown(s: RunSummary): string {
  const status = s.failed === 0 ? "✅ All prompt tests passed" : `❌ ${s.failed} prompt test(s) failed`;
  const lines = [
    `### ${status}`,
    ``,
    `**${s.passed}/${s.total} passed** · ~$${s.costUsd.toFixed(4)}${s.mock ? " · _mock mode_" : ""}`,
    ``,
    `| Result | Test | Failed checks |`,
    `| --- | --- | --- |`,
  ];
  for (const r of s.results) {
    const fails = r.error ? r.error : r.assertions.filter((a) => !a.pass).map((a) => `${a.type}: ${a.message}`).join("; ");
    lines.push(`| ${r.pass ? "✅" : "❌"} | ${r.suite} › ${r.name} | ${fails || "—"} |`);
  }
  lines.push(``, `<sub>Generated by [prompttest](https://github.com/Mushaim/prompttest)</sub>`);
  return lines.join("\n");
}
